### ISSUE TITLE
[509] "Classic Trumpet" is named "Trumpet :" in Starlight Dream 1

### ISSUE THREAD

**Issue by StrixSoftware** [Stardream-Studios/SoundFont-Projects#1]
### _This is an example of an issue for Stardream Studios SoundFont Projects._

**SoundFont Name:**
Starlight Dream 1. The current name is listed on the Trello Board and the official website, however an outdated tone name is found in Starlight Dream 1.

**Patch Number:**
Bank 2 Program 57.

**Tone Names:**
The current name found in Starlight Dream 1 is "Trumpet :", when it should be "Classic Trumpet". This name can no longer be used as ":" (legato enabled tones) cannot be used in any samplers, not only SoundFonts.

**Explanation:**
Using this tone may result in a different sound to what is expected if reference is only made to the official website and/or Trello Board.

**Comment by LoveBodhi** [comment]
Legato cannot be done on any samplers.
